# Generated by Django 2.2.5 on 2021-12-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211227_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curreny',
            new_name='currency',
        ),
    ]
