# Generated by Django 2.2.5 on 2021-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211228_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='langauge',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('korean', 'Korean')], max_length=2, null=True),
        ),
    ]
