# Generated by Django 2.2.5 on 2021-12-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20211231_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='counry',
            new_name='country',
        ),
    ]
